# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AUST_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icon_rc
from Mywidget import MListWidget,MLineEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(585, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(131, 421))
        self.frame_3.setMaximumSize(QtCore.QSize(131, 16777215))
        self.frame_3.setStyleSheet("QFrame#frame_3{\n"
"    background-color: qlineargradient(x0:0, y0:1, x2:0, y2:1,stop:0 rgb(200, 100, 255), stop:1 rgb(0, 200, 255));\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.frame_3)
        self.logo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logo.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: bold 25pt \"Snap ITC\";")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icon/icon/AUST.svg"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setIndent(-1)
        self.logo.setOpenExternalLinks(False)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.list_main = QtWidgets.QListWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_main.sizePolicy().hasHeightForWidth())
        self.list_main.setSizePolicy(sizePolicy)
        self.list_main.setMinimumSize(QtCore.QSize(0, 227))
        self.list_main.setStyleSheet("QListView {\n"
"    font: bold  15px \"Microsoft YaHei\";\n"
"    border-radius: 20px;\n"
"    color: rgba(255, 255, 255);\n"
"    background-color: transparent;\n"
"    outline:0px;\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:45px;\n"
"padding-left:12px;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: rgba(130, 117, 255, 87);\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"background-color: rgba(100, 250, 254,150);\n"
"color: rgba(255, 255, 255,255);\n"
"border-left: 2px solid rgb(255, 255, 255);\n"
"outline: none;\n"
"}\n"
"\n"
"")
        self.list_main.setObjectName("list_main")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/white/buttom_white/instagram_instagram-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.list_main.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/white/buttom_white/火箭_rocket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.list_main.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/white/buttom_white/井号文件1_file-hash-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.list_main.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/white/buttom_white/发送1_send-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.list_main.addItem(item)
        self.verticalLayout.addWidget(self.list_main)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame#frame{\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border:5px outset rgb(0,245,255);\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: bold 15pt \"Microsoft YaHei\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pic_list = MListWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic_list.sizePolicy().hasHeightForWidth())
        self.pic_list.setSizePolicy(sizePolicy)
        self.pic_list.setAcceptDrops(True)
        self.pic_list.setStyleSheet("QListWidget{\n"
"background-color: rgba(165, 205, 255,125);\n"
"font: bold 16pt \"Microsoft YaHei\";\n"
"border:2px outset rgb(0, 0, 0);\n"
"border-radius:8px;\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"height:30px;\n"
"padding-left:12px;\n"
"}\n"
"QListView:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgb(0, 0, 0);\n"
"}\n"
"QListView::item:selected {\n"
"    /*background-color: transparent;*/\n"
"    background-color: rgba(165, 150, 255,150);\n"
"    color: rgb(0, 0, 0,);\n"
"}")
        self.pic_list.setObjectName("pic_list")
        self.verticalLayout_2.addWidget(self.pic_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pic_input = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic_input.sizePolicy().hasHeightForWidth())
        self.pic_input.setSizePolicy(sizePolicy)
        self.pic_input.setMinimumSize(QtCore.QSize(120, 60))
        self.pic_input.setMaximumSize(QtCore.QSize(150, 75))
        self.pic_input.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgba(165, 205, 255,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold  18px \"Microsoft YaHei\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 205, 255,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.pic_input.setObjectName("pic_input")
        self.horizontalLayout.addWidget(self.pic_input)
        self.pic_clear = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic_clear.sizePolicy().hasHeightForWidth())
        self.pic_clear.setSizePolicy(sizePolicy)
        self.pic_clear.setMinimumSize(QtCore.QSize(120, 60))
        self.pic_clear.setMaximumSize(QtCore.QSize(150, 75))
        self.pic_clear.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgba(165, 205, 255,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold  18px \"Microsoft YaHei\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 205, 255,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.pic_clear.setObjectName("pic_clear")
        self.horizontalLayout.addWidget(self.pic_clear)
        self.pic_clearall = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pic_clearall.sizePolicy().hasHeightForWidth())
        self.pic_clearall.setSizePolicy(sizePolicy)
        self.pic_clearall.setMinimumSize(QtCore.QSize(120, 60))
        self.pic_clearall.setMaximumSize(QtCore.QSize(150, 75))
        self.pic_clearall.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgba(165, 205, 255,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold  18px \"Microsoft YaHei\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 205, 255,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.pic_clearall.setObjectName("pic_clearall")
        self.horizontalLayout.addWidget(self.pic_clearall)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setStyleSheet("QFrame#frame_5\n"
"{\n"
"font: bold 15pt \"Microsoft YaHei\";\n"
"     border-color: rgb(156, 156, 156);\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-radius:10px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_51 = QtWidgets.QLabel(self.frame_5)
        self.label_51.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_50.addWidget(self.label_51)
        self.cb_SR = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_SR.sizePolicy().hasHeightForWidth())
        self.cb_SR.setSizePolicy(sizePolicy)
        self.cb_SR.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_SR.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_SR.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_SR.setObjectName("cb_SR")
        self.cb_SR.addItem("")
        self.cb_SR.addItem("")
        self.cb_SR.addItem("")
        self.cb_SR.addItem("")
        self.horizontalLayout_50.addWidget(self.cb_SR)
        self.horizontalLayout_50.setStretch(0, 1)
        self.horizontalLayout_50.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_50, 0, 0, 1, 1)
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_14)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.page_14)
        self.label_7.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.cb_model_cgncnn = QtWidgets.QComboBox(self.page_14)
        self.cb_model_cgncnn.setMinimumSize(QtCore.QSize(100, 30))
        self.cb_model_cgncnn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_model_cgncnn.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_model_cgncnn.setObjectName("cb_model_cgncnn")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.cb_model_cgncnn.addItem("")
        self.verticalLayout_3.addWidget(self.cb_model_cgncnn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.page_14)
        self.label_6.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cb_syncgap_cgncnn = QtWidgets.QComboBox(self.page_14)
        self.cb_syncgap_cgncnn.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_syncgap_cgncnn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_syncgap_cgncnn.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_syncgap_cgncnn.setObjectName("cb_syncgap_cgncnn")
        self.cb_syncgap_cgncnn.addItem("")
        self.cb_syncgap_cgncnn.addItem("")
        self.cb_syncgap_cgncnn.addItem("")
        self.cb_syncgap_cgncnn.addItem("")
        self.horizontalLayout_2.addWidget(self.cb_syncgap_cgncnn)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.page_14)
        self.label_9.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.cb_ns_cgncnn = QtWidgets.QComboBox(self.page_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_ns_cgncnn.sizePolicy().hasHeightForWidth())
        self.cb_ns_cgncnn.setSizePolicy(sizePolicy)
        self.cb_ns_cgncnn.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_ns_cgncnn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_ns_cgncnn.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_ns_cgncnn.setObjectName("cb_ns_cgncnn")
        self.cb_ns_cgncnn.addItem("")
        self.cb_ns_cgncnn.addItem("")
        self.cb_ns_cgncnn.addItem("")
        self.cb_ns_cgncnn.addItem("")
        self.cb_ns_cgncnn.addItem("")
        self.horizontalLayout_11.addWidget(self.cb_ns_cgncnn)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_10 = QtWidgets.QLabel(self.page_14)
        self.label_10.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.stackedWidget_4.addWidget(self.page_14)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.cb_model_esrncnn = QtWidgets.QComboBox(self.page_3)
        self.cb_model_esrncnn.setMinimumSize(QtCore.QSize(100, 30))
        self.cb_model_esrncnn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_model_esrncnn.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_model_esrncnn.setObjectName("cb_model_esrncnn")
        self.cb_model_esrncnn.addItem("")
        self.cb_model_esrncnn.addItem("")
        self.cb_model_esrncnn.addItem("")
        self.cb_model_esrncnn.addItem("")
        self.cb_model_esrncnn.addItem("")
        self.verticalLayout_5.addWidget(self.cb_model_esrncnn)
        spacerItem5 = QtWidgets.QSpacerItem(20, 176, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.stackedWidget_4.addWidget(self.page_3)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.page_8)
        self.label_17.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.cb_model_wfncnn = QtWidgets.QComboBox(self.page_8)
        self.cb_model_wfncnn.setMinimumSize(QtCore.QSize(100, 30))
        self.cb_model_wfncnn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_model_wfncnn.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_model_wfncnn.setObjectName("cb_model_wfncnn")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.cb_model_wfncnn.addItem("")
        self.verticalLayout_7.addWidget(self.cb_model_wfncnn)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.page_8)
        self.label_13.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.cb_ns_wfncnn = QtWidgets.QComboBox(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_ns_wfncnn.sizePolicy().hasHeightForWidth())
        self.cb_ns_wfncnn.setSizePolicy(sizePolicy)
        self.cb_ns_wfncnn.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_ns_wfncnn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_ns_wfncnn.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_ns_wfncnn.setObjectName("cb_ns_wfncnn")
        self.cb_ns_wfncnn.addItem("")
        self.cb_ns_wfncnn.addItem("")
        self.cb_ns_wfncnn.addItem("")
        self.cb_ns_wfncnn.addItem("")
        self.cb_ns_wfncnn.addItem("")
        self.horizontalLayout_14.addWidget(self.cb_ns_wfncnn)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        spacerItem7 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.stackedWidget_4.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.page_9)
        self.label_18.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.cb_model_srmdncnn = QtWidgets.QComboBox(self.page_9)
        self.cb_model_srmdncnn.setMinimumSize(QtCore.QSize(100, 30))
        self.cb_model_srmdncnn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_model_srmdncnn.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_model_srmdncnn.setObjectName("cb_model_srmdncnn")
        self.cb_model_srmdncnn.addItem("")
        self.cb_model_srmdncnn.addItem("")
        self.cb_model_srmdncnn.addItem("")
        self.cb_model_srmdncnn.addItem("")
        self.cb_model_srmdncnn.addItem("")
        self.cb_model_srmdncnn.addItem("")
        self.verticalLayout_8.addWidget(self.cb_model_srmdncnn)
        spacerItem8 = QtWidgets.QSpacerItem(20, 176, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.stackedWidget_4.addWidget(self.page_9)
        self.gridLayout_3.addWidget(self.stackedWidget_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 190))
        self.groupBox_8.setStyleSheet("QGroupBox\n"
"{\n"
"     font: bold 15pt \"Microsoft YaHei\";\n"
"     border-color: rgb(156, 156, 156);\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-radius:10px;\n"
"     margin-top: 28px;\n"
"     \n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"left: 5px;\n"
"top:0px;\n"
"}")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rb_SR = QtWidgets.QRadioButton(self.groupBox_8)
        self.rb_SR.setStyleSheet("QRadioButton{\n"
"  spacing:12px;\n"
"  color: rgb(0, 0, 0);\n"
"  background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(200, 170, 254),  stop:1 rgb(200, 170, 254));\n"
"  border:1px outset rgb(255, 255, 255);\n"
"  border-radius:8px;\n"
"  padding:4px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold 18px \"Microsoft YaHei\"\n"
"}\n"
"QRadioButton:hover {\n"
"  background-color:rgb(180, 170, 254);\n"
"  border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QRadioButton:pressed {\n"
"  background-color:rgb(160, 170, 254);\n"
"  border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.rb_SR.setCheckable(True)
        self.rb_SR.setChecked(True)
        self.rb_SR.setAutoExclusive(False)
        self.rb_SR.setObjectName("rb_SR")
        self.verticalLayout_6.addWidget(self.rb_SR)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.cb_gpuid_sr = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_gpuid_sr.sizePolicy().hasHeightForWidth())
        self.cb_gpuid_sr.setSizePolicy(sizePolicy)
        self.cb_gpuid_sr.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_gpuid_sr.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_gpuid_sr.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_gpuid_sr.setObjectName("cb_gpuid_sr")
        self.cb_gpuid_sr.addItem("")
        self.cb_gpuid_sr.addItem("")
        self.cb_gpuid_sr.addItem("")
        self.cb_gpuid_sr.addItem("")
        self.cb_gpuid_sr.addItem("")
        self.horizontalLayout_9.addWidget(self.cb_gpuid_sr)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.cb_tilesize = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_tilesize.sizePolicy().hasHeightForWidth())
        self.cb_tilesize.setSizePolicy(sizePolicy)
        self.cb_tilesize.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_tilesize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_tilesize.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_tilesize.setObjectName("cb_tilesize")
        self.cb_tilesize.addItem("")
        self.cb_tilesize.addItem("")
        self.cb_tilesize.addItem("")
        self.cb_tilesize.addItem("")
        self.cb_tilesize.addItem("")
        self.cb_tilesize.addItem("")
        self.horizontalLayout_13.addWidget(self.cb_tilesize)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.horizontalLayout_13.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.rb_tta = QtWidgets.QRadioButton(self.groupBox_8)
        self.rb_tta.setStyleSheet("QRadioButton{\n"
"  spacing:12px;\n"
"  color: rgb(0, 0, 0);\n"
"  background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(66, 226, 192),  stop:1 rgb(66, 250, 192));\n"
"  border:1px outset rgb(255, 255, 255);\n"
"  border-radius:8px;\n"
"  padding:4px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold 18px \"Microsoft YaHei\"\n"
"}\n"
"QRadioButton:hover {\n"
"  background-color:rgb(50, 250, 180);\n"
"  border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QRadioButton:pressed {\n"
"  background-color:rgb(66, 250, 192);\n"
"  border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.rb_tta.setChecked(False)
        self.rb_tta.setAutoExclusive(False)
        self.rb_tta.setObjectName("rb_tta")
        self.verticalLayout_6.addWidget(self.rb_tta)
        self.gridLayout_4.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox\n"
"{\n"
"     font: bold 15pt \"Microsoft YaHei\";\n"
"     border-color: rgb(156, 156, 156);\n"
"     border-width: 2px;\n"
"     border-style: solid;\n"
"     border-radius:10px;\n"
"     margin-top: 28px;\n"
"     \n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"left: 5px;\n"
"top:0px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_save_alpha = QtWidgets.QRadioButton(self.groupBox)
        self.rb_save_alpha.setStyleSheet("QRadioButton{\n"
"  spacing:12px;\n"
"  color: rgb(0, 0, 0);\n"
"  background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(66, 226, 192),  stop:1 rgb(66, 250, 192));\n"
"  border:1px outset rgb(255, 255, 255);\n"
"  border-radius:8px;\n"
"  padding:4px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold 18px \"Microsoft YaHei\"\n"
"}\n"
"QRadioButton:hover {\n"
"  background-color:rgb(50, 250, 180);\n"
"  border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QRadioButton:pressed {\n"
"  background-color:rgb(66, 250, 192);\n"
"  border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.rb_save_alpha.setChecked(True)
        self.rb_save_alpha.setObjectName("rb_save_alpha")
        self.verticalLayout_4.addWidget(self.rb_save_alpha)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.cb_PicFormat = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_PicFormat.sizePolicy().hasHeightForWidth())
        self.cb_PicFormat.setSizePolicy(sizePolicy)
        self.cb_PicFormat.setMinimumSize(QtCore.QSize(0, 30))
        self.cb_PicFormat.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cb_PicFormat.setStyleSheet("QComboBox\n"
"{\n"
"    border-radius:5px;\n"
"    background-color:rgb(165, 205, 255);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    padding-top: 2px;\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:disabled\n"
"{\n"
"    background-color:rgba(50,50,50,200);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(160,160,160);\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*点击combox的样式*/\n"
"QComboBox:on\n"
"{\n"
"    border-radius:3px;\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"/*下拉框的样式*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"    outline: 0px solid gray;  /*取消选中虚线*/\n"
"    border: 1px solid rgb(31,156,220);  \n"
"    font: 75 9pt \"Microsoft YaHei\";\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    selection-background-color: rgb(90,90,90);   \n"
"}\n"
" /*选中每一项高度*/\n"
"QComboBox QAbstractItemView::item\n"
" { \n"
"    height: 25px;  \n"
" }\n"
"/*选中每一项的字体颜色和背景颜色*/\n"
"QComboBox QAbstractItemView::item:selected \n"
"{\n"
"    color: rgb(31,163,246);\n"
"    background-color: rgb(0,0,0); \n"
"}\n"
" /*下拉箭头的边框*/\n"
"QComboBox::drop-down \n"
"{\n"
"    border:none;\n"
"}\n"
" /*下拉箭头样式*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    right:10px;/*控制箭头左右偏移*/\n"
"    width: 9px;  \n"
"    height: 9px; \n"
"  border-image: url(:/white/buttom_white/下1_down-two.svg);\n"
"      border-width:8px 8px 8px 8px;\n"
"}\n"
" /*下拉箭头点击样式*/\n"
"QComboBox::down-arrow:on\n"
"{\n"
"    width: 9px;  \n"
"    height: 9px;   \n"
"    border-image: url(:/white/buttom_white/上1_up-two.svg);\n"
"    border-width:8px 8px 8px 8px;\n"
"}")
        self.cb_PicFormat.setObjectName("cb_PicFormat")
        self.cb_PicFormat.addItem("")
        self.cb_PicFormat.addItem("")
        self.horizontalLayout_10.addWidget(self.cb_PicFormat)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.page_7)
        self.label_12.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.sb_quality_jpg = QtWidgets.QSpinBox(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_quality_jpg.sizePolicy().hasHeightForWidth())
        self.sb_quality_jpg.setSizePolicy(sizePolicy)
        self.sb_quality_jpg.setStyleSheet("QSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    padding-left: 4px;\n"
"    padding-right: 15px;\n"
"    border:2px solid rgb(253, 139, 133);\n"
"    border-radius:5px;\n"
"    color: rgb(200,200,200);\n"
"    background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"    selection-color: rgb(235,235,235);\n"
"    selection-background-color: rgb(83,121,180);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    \n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"       background-color: rgb(248, 194, 152);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"\n"
"QSpinBox::up-button { /* 向上按钮 */\n"
"    subcontrol-origin: border; /* 起始位置 */\n"
"    subcontrol-position: top right; /* 居于右上角 */\n"
"    border: none;\n"
"    width: 12px;\n"
"    margin-top: 2px;\n"
"    margin-right: 13px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox::up-arrow { /* 向上箭头，图片大小为8x8 */\n"
"    image: url(:/white/buttom_white/上-小_up-small.svg);\n"
"}\n"
"\n"
"QSpinBox::up-arrow:hover {\n"
"    image: url(:/white/buttom_white/上-小_up-small.svg);\n"
"}\n"
"\n"
"QSpinBox::up-arrow:disabled, QSpinBox::up-arrow:off {\n"
"    image: url(:/white/buttom_white/上-小_up-small.svg);\n"
"}\n"
"\n"
"QSpinBox::down-button { /* 向下按钮 */\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    border: none;\n"
"    width: 12px;\n"
"    margin-top: 0px;\n"
"    margin-right: 13px;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox::down-arrow { /* 向下箭头 */\n"
"    image: url(:/white/buttom_white/下-小_down-small.svg);\n"
"}\n"
"\n"
"QSpinBox::down-arrow:hover {\n"
"    image: url(:/white/buttom_white/下-小_down-small.svg);\n"
"}\n"
"\n"
"QSpinBox::down-arrow:disabled, QSpinBox::down-arrow:off {\n"
"    image: url(:/white/buttom_white/下-小_down-small.svg);\n"
"}")
        self.sb_quality_jpg.setMinimum(1)
        self.sb_quality_jpg.setMaximum(100)
        self.sb_quality_jpg.setProperty("value", 100)
        self.sb_quality_jpg.setObjectName("sb_quality_jpg")
        self.horizontalLayout_12.addWidget(self.sb_quality_jpg)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.gridLayout_7.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.page_6)
        self.label_15.setStyleSheet("font: bold 13pt \"Microsoft YaHei\";")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.sb_compress_png = QtWidgets.QSpinBox(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_compress_png.sizePolicy().hasHeightForWidth())
        self.sb_compress_png.setSizePolicy(sizePolicy)
        self.sb_compress_png.setStyleSheet("QSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    padding-left: 4px;\n"
"    padding-right: 15px;\n"
"    border:2px solid rgb(253, 139, 133);\n"
"    border-radius:5px;\n"
"    color: rgb(200,200,200);\n"
"    background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"    selection-color: rgb(235,235,235);\n"
"    selection-background-color: rgb(83,121,180);\n"
"    font: bold 13pt \"Microsoft YaHei\";\n"
"    color:rgb(0,0,0);\n"
"    \n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"       background-color: rgb(248, 194, 152);\n"
"    border:1px solid rgb(31,156,220) ;\n"
"}\n"
"\n"
"QSpinBox::up-button { /* 向上按钮 */\n"
"    subcontrol-origin: border; /* 起始位置 */\n"
"    subcontrol-position: top right; /* 居于右上角 */\n"
"    border: none;\n"
"    width: 12px;\n"
"    margin-top: 2px;\n"
"    margin-right: 13px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox::up-arrow { /* 向上箭头，图片大小为8x8 */\n"
"    image: url(:/white/buttom_white/上-小_up-small.svg);\n"
"}\n"
"\n"
"QSpinBox::up-arrow:hover {\n"
"    image: url(:/white/buttom_white/上-小_up-small.svg);\n"
"}\n"
"\n"
"QSpinBox::up-arrow:disabled, QSpinBox::up-arrow:off {\n"
"    image: url(:/white/buttom_white/上-小_up-small.svg);\n"
"}\n"
"\n"
"QSpinBox::down-button { /* 向下按钮 */\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    border: none;\n"
"    width: 12px;\n"
"    margin-top: 0px;\n"
"    margin-right: 13px;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox::down-arrow { /* 向下箭头 */\n"
"    image: url(:/white/buttom_white/下-小_down-small.svg);\n"
"}\n"
"\n"
"QSpinBox::down-arrow:hover {\n"
"    image: url(:/white/buttom_white/下-小_down-small.svg);\n"
"}\n"
"\n"
"QSpinBox::down-arrow:disabled, QSpinBox::down-arrow:off {\n"
"    image: url(:/white/buttom_white/下-小_down-small.svg);\n"
"}")
        self.sb_compress_png.setMinimum(0)
        self.sb_compress_png.setMaximum(9)
        self.sb_compress_png.setProperty("value", 9)
        self.sb_compress_png.setObjectName("sb_compress_png")
        self.horizontalLayout_15.addWidget(self.sb_compress_png)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 1)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("font: bold 15pt \"Microsoft YaHei\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.out_folder = MLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_folder.sizePolicy().hasHeightForWidth())
        self.out_folder.setSizePolicy(sizePolicy)
        self.out_folder.setMinimumSize(QtCore.QSize(0, 40))
        self.out_folder.setStyleSheet("QLineEdit{\n"
"background-color: rgba(165, 205, 255,125);\n"
"font: bold 15pt \"Microsoft YaHei\";\n"
"border:2px outset rgb(0, 0, 0);\n"
"border-radius:8px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgb(0, 0, 0);\n"
"}\n"
"")
        self.out_folder.setInputMask("")
        self.out_folder.setText("")
        self.out_folder.setReadOnly(True)
        self.out_folder.setObjectName("out_folder")
        self.verticalLayout_4.addWidget(self.out_folder)
        self.select_of = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_of.sizePolicy().hasHeightForWidth())
        self.select_of.setSizePolicy(sizePolicy)
        self.select_of.setMinimumSize(QtCore.QSize(80, 40))
        self.select_of.setMaximumSize(QtCore.QSize(120, 60))
        self.select_of.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgba(165, 205, 255,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold  18px \"Microsoft YaHei\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 205, 255,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.select_of.setObjectName("select_of")
        self.verticalLayout_4.addWidget(self.select_of)
        spacerItem14 = QtWidgets.QSpacerItem(20, 223, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(4, 2)
        self.verticalLayout_4.setStretch(5, 1)
        self.verticalLayout_4.setStretch(6, 1000)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.stop_render = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_render.sizePolicy().hasHeightForWidth())
        self.stop_render.setSizePolicy(sizePolicy)
        self.stop_render.setMinimumSize(QtCore.QSize(0, 50))
        self.stop_render.setMaximumSize(QtCore.QSize(150, 75))
        self.stop_render.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgba(165, 205, 255,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold  18px \"Microsoft YaHei\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100, 100, 255,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.stop_render.setObjectName("stop_render")
        self.horizontalLayout_3.addWidget(self.stop_render)
        self.start_render = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_render.sizePolicy().hasHeightForWidth())
        self.start_render.setSizePolicy(sizePolicy)
        self.start_render.setMinimumSize(QtCore.QSize(0, 50))
        self.start_render.setMaximumSize(QtCore.QSize(150, 75))
        self.start_render.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgba(165, 205, 255,125);\n"
"    border:1px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"    font: bold  18px \"Microsoft YaHei\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(165, 205, 255,80%);\n"
"    border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100, 100, 255,90%);\n"
"    border:4px outset rgba(36, 36, 36,0);\n"
"}")
        self.start_render.setObjectName("start_render")
        self.horizontalLayout_3.addWidget(self.start_render)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.te_show = QtWidgets.QTextEdit(self.page_5)
        self.te_show.setStyleSheet("QTextEdit{\n"
"background-color: rgb(220,220, 255);\n"
"font: bold 15pt \"Microsoft YaHei\";\n"
"border:2px outset rgb(0, 0, 0);\n"
"border-radius:8px;\n"
"}\n"
"QTextEdit:hover {\n"
"    background-color: rgb(200,200, 255);\n"
"    border:2px outset rgb(0, 0, 0);\n"
"}\n"
"")
        self.te_show.setReadOnly(True)
        self.te_show.setObjectName("te_show")
        self.gridLayout_6.addWidget(self.te_show, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.list_main.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_4.setCurrentIndex(0)
        self.cb_syncgap_cgncnn.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(0)
        self.cb_PicFormat.activated['int'].connect(self.stackedWidget_2.setCurrentIndex) # type: ignore
        self.list_main.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        self.cb_SR.activated['int'].connect(self.stackedWidget_4.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AUST 2.0 适用于二次元图片超分辨率的开源工具"))
        self.list_main.setSortingEnabled(False)
        __sortingEnabled = self.list_main.isSortingEnabled()
        self.list_main.setSortingEnabled(False)
        item = self.list_main.item(0)
        item.setText(_translate("MainWindow", "输入设置"))
        item = self.list_main.item(1)
        item.setText(_translate("MainWindow", "超分设置"))
        item = self.list_main.item(2)
        item.setText(_translate("MainWindow", "输出设置"))
        item = self.list_main.item(3)
        item.setText(_translate("MainWindow", "交付"))
        self.list_main.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "图片输入：（可直接拖入文件）"))
        self.pic_input.setText(_translate("MainWindow", "导入"))
        self.pic_clear.setText(_translate("MainWindow", "清除选中项"))
        self.pic_clearall.setText(_translate("MainWindow", "清空"))
        self.label_51.setText(_translate("MainWindow", "超分算法:"))
        self.cb_SR.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">超分算法：</span></p><p><span style=\" font-size:11pt; font-weight:600;\">Real_cugan:动漫超分五边形战士，适用于大多数动漫场景，在不了解其他模型的情况下选这个算法就对了。</span></p><p><br/></p></body></html>"))
        self.cb_SR.setItemText(0, _translate("MainWindow", "Real_cugan_ncnn"))
        self.cb_SR.setItemText(1, _translate("MainWindow", "Real_esrgan_ncnn"))
        self.cb_SR.setItemText(2, _translate("MainWindow", "waifu2x_ncnn"))
        self.cb_SR.setItemText(3, _translate("MainWindow", "srmd_ncnn"))
        self.label_7.setText(_translate("MainWindow", "模型选择:"))
        self.cb_model_cgncnn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">带有pro的是最新的模型，带有Lastst是老模型。新效果会更好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">up后面跟的数字是放大的倍数。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有conservative的是相对保守的模型。对细节处理很好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有no-denoise的是无降噪模型。在干净的画面里有较好的表现。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有denoise的是降噪模型。倾向于涂抹，锐化，降噪。</span></p></body></html>"))
        self.cb_model_cgncnn.setItemText(0, _translate("MainWindow", "pro-conservative-up2x"))
        self.cb_model_cgncnn.setItemText(1, _translate("MainWindow", "pro-conservative-up3x"))
        self.cb_model_cgncnn.setItemText(2, _translate("MainWindow", "pro-denoise3x-up2x"))
        self.cb_model_cgncnn.setItemText(3, _translate("MainWindow", "pro-denoise3x-up3x"))
        self.cb_model_cgncnn.setItemText(4, _translate("MainWindow", "pro-no-denoise-up2x"))
        self.cb_model_cgncnn.setItemText(5, _translate("MainWindow", "pro-no-denoise-up3x"))
        self.cb_model_cgncnn.setItemText(6, _translate("MainWindow", "up2x-latest-conservative"))
        self.cb_model_cgncnn.setItemText(7, _translate("MainWindow", "up2x-latest-denoise1x"))
        self.cb_model_cgncnn.setItemText(8, _translate("MainWindow", "up2x-latest-denoise2x"))
        self.cb_model_cgncnn.setItemText(9, _translate("MainWindow", "up2x-latest-denoise3x"))
        self.cb_model_cgncnn.setItemText(10, _translate("MainWindow", "up2x-latest-no-denoise"))
        self.cb_model_cgncnn.setItemText(11, _translate("MainWindow", "up3x-latest-conservative"))
        self.cb_model_cgncnn.setItemText(12, _translate("MainWindow", "up3x-latest-denoise3x"))
        self.cb_model_cgncnn.setItemText(13, _translate("MainWindow", "up3x-latest-no-denoise"))
        self.cb_model_cgncnn.setItemText(14, _translate("MainWindow", "up4x-latest-conservative"))
        self.cb_model_cgncnn.setItemText(15, _translate("MainWindow", "up4x-latest-denoise3x"))
        self.cb_model_cgncnn.setItemText(16, _translate("MainWindow", "up4x-latest-no-denoise"))
        self.label_6.setText(_translate("MainWindow", "syncgap:"))
        self.cb_syncgap_cgncnn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">syncgap-mode是一个速度和效果的trade-off。由于省显存需要，需要对全图进行分块分别处理，分别处理最后汇总成处理完的大图，整个pipeline中，有一些位置需要对一些gap参数同步（sync-gap）</span></p><p><span style=\" font-size:10pt; font-weight:600;\">0最快：不同patch之间可能造成切割线</span></p><p><span style=\" font-size:10pt; font-weight:600;\">1最慢：效果无损</span></p><p><span style=\" font-size:10pt; font-weight:600;\">2速度适中：稍微对背景虚化的保留损失一点，纹理没什么损失</span></p><p><span style=\" font-size:10pt; font-weight:600;\">3最快：相比2对背景虚化的保留损失更多一点，纹理没什么损失</span></p></body></html>"))
        self.cb_syncgap_cgncnn.setItemText(0, _translate("MainWindow", "0"))
        self.cb_syncgap_cgncnn.setItemText(1, _translate("MainWindow", "1"))
        self.cb_syncgap_cgncnn.setItemText(2, _translate("MainWindow", "2"))
        self.cb_syncgap_cgncnn.setItemText(3, _translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", "线程数:"))
        self.cb_ns_cgncnn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">在一定范围内，增大线程数可以提高运行速度。</span></p></body></html>"))
        self.cb_ns_cgncnn.setItemText(0, _translate("MainWindow", "1"))
        self.cb_ns_cgncnn.setItemText(1, _translate("MainWindow", "2"))
        self.cb_ns_cgncnn.setItemText(2, _translate("MainWindow", "3"))
        self.cb_ns_cgncnn.setItemText(3, _translate("MainWindow", "4"))
        self.cb_ns_cgncnn.setItemText(4, _translate("MainWindow", "5"))
        self.label_10.setText(_translate("MainWindow", "提示：将鼠标放到控件上会有相关的参数说明"))
        self.label_16.setText(_translate("MainWindow", "模型选择:"))
        self.cb_model_esrncnn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">带有pro的是最新的模型，带有Lastst是老模型。新效果会更好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">up后面跟的数字是放大的倍数。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有conservative的是相对保守的模型。对细节处理很好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有no-denoise的是无降噪模型。在干净的画面里有较好的表现。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有denoise的是降噪模型。倾向于涂抹，锐化，降噪。</span></p></body></html>"))
        self.cb_model_esrncnn.setItemText(0, _translate("MainWindow", "realesr-animevideov3-x2"))
        self.cb_model_esrncnn.setItemText(1, _translate("MainWindow", "realesr-animevideov3-x3"))
        self.cb_model_esrncnn.setItemText(2, _translate("MainWindow", "realesr-animevideov3-x4"))
        self.cb_model_esrncnn.setItemText(3, _translate("MainWindow", "realesrgan-x4plus"))
        self.cb_model_esrncnn.setItemText(4, _translate("MainWindow", "realesrgan-x4plus-anime"))
        self.label_17.setText(_translate("MainWindow", "模型选择:"))
        self.cb_model_wfncnn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">带有pro的是最新的模型，带有Lastst是老模型。新效果会更好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">up后面跟的数字是放大的倍数。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有conservative的是相对保守的模型。对细节处理很好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有no-denoise的是无降噪模型。在干净的画面里有较好的表现。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有denoise的是降噪模型。倾向于涂抹，锐化，降噪。</span></p></body></html>"))
        self.cb_model_wfncnn.setItemText(0, _translate("MainWindow", "cunet_noise0"))
        self.cb_model_wfncnn.setItemText(1, _translate("MainWindow", "cunet_noise0_scale2.0x"))
        self.cb_model_wfncnn.setItemText(2, _translate("MainWindow", "cunet_noise1"))
        self.cb_model_wfncnn.setItemText(3, _translate("MainWindow", "cunet_noise1_scale2.0x"))
        self.cb_model_wfncnn.setItemText(4, _translate("MainWindow", "cunet_noise2"))
        self.cb_model_wfncnn.setItemText(5, _translate("MainWindow", "cunet_noise2_scale2.0x"))
        self.cb_model_wfncnn.setItemText(6, _translate("MainWindow", "cunet_noise3"))
        self.cb_model_wfncnn.setItemText(7, _translate("MainWindow", "cunet_noise3_scale2.0x"))
        self.cb_model_wfncnn.setItemText(8, _translate("MainWindow", "cunet_scale2.0x"))
        self.cb_model_wfncnn.setItemText(9, _translate("MainWindow", "anime_noise0_scale2.0x"))
        self.cb_model_wfncnn.setItemText(10, _translate("MainWindow", "anime_noise1_scale2.0x"))
        self.cb_model_wfncnn.setItemText(11, _translate("MainWindow", "anime_noise2_scale2.0x"))
        self.cb_model_wfncnn.setItemText(12, _translate("MainWindow", "anime_noise3_scale2.0x"))
        self.cb_model_wfncnn.setItemText(13, _translate("MainWindow", "anime_scale2.0x"))
        self.cb_model_wfncnn.setItemText(14, _translate("MainWindow", "photo_noise0_scale2.0x"))
        self.cb_model_wfncnn.setItemText(15, _translate("MainWindow", "photo_noise1_scale2.0x"))
        self.cb_model_wfncnn.setItemText(16, _translate("MainWindow", "photo_noise2_scale2.0x"))
        self.cb_model_wfncnn.setItemText(17, _translate("MainWindow", "photo_noise3_scale2.0x"))
        self.cb_model_wfncnn.setItemText(18, _translate("MainWindow", "photo_scale2.0x"))
        self.label_13.setText(_translate("MainWindow", "线程数:"))
        self.cb_ns_wfncnn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">在一定范围内，增大线程数可以提高运行速度。</span></p></body></html>"))
        self.cb_ns_wfncnn.setItemText(0, _translate("MainWindow", "1"))
        self.cb_ns_wfncnn.setItemText(1, _translate("MainWindow", "2"))
        self.cb_ns_wfncnn.setItemText(2, _translate("MainWindow", "3"))
        self.cb_ns_wfncnn.setItemText(3, _translate("MainWindow", "4"))
        self.cb_ns_wfncnn.setItemText(4, _translate("MainWindow", "5"))
        self.label_18.setText(_translate("MainWindow", "模型选择:"))
        self.cb_model_srmdncnn.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">带有pro的是最新的模型，带有Lastst是老模型。新效果会更好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">up后面跟的数字是放大的倍数。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有conservative的是相对保守的模型。对细节处理很好。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有no-denoise的是无降噪模型。在干净的画面里有较好的表现。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">带有denoise的是降噪模型。倾向于涂抹，锐化，降噪。</span></p></body></html>"))
        self.cb_model_srmdncnn.setItemText(0, _translate("MainWindow", "srmd_x2"))
        self.cb_model_srmdncnn.setItemText(1, _translate("MainWindow", "srmd_x3"))
        self.cb_model_srmdncnn.setItemText(2, _translate("MainWindow", "srmd_x4"))
        self.cb_model_srmdncnn.setItemText(3, _translate("MainWindow", "srmdnf_x2"))
        self.cb_model_srmdncnn.setItemText(4, _translate("MainWindow", "srmdnf_x3"))
        self.cb_model_srmdncnn.setItemText(5, _translate("MainWindow", "srmdnf_x4"))
        self.groupBox_8.setTitle(_translate("MainWindow", "超分设置"))
        self.rb_SR.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">超分进程的启动开关。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">关闭后会跳过超分进程直接输出，常用于转换图片格式。</span></p></body></html>"))
        self.rb_SR.setText(_translate("MainWindow", "启动超分渲染"))
        self.label_8.setText(_translate("MainWindow", "负载显卡代码:"))
        self.cb_gpuid_sr.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">0：代表计算机里的第一张显卡</span></p><p><span style=\" font-size:10pt; font-weight:600;\">1：代表计算机里的第二张显卡</span></p><p><span style=\" font-size:10pt; font-weight:600;\">2：代表计算机里的第三张显卡</span></p><p><span style=\" font-size:10pt; font-weight:600;\">以此类推。包括核显。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">只有一个显卡的机器用参数 0 即可</span></p><p><span style=\" font-size:10pt; font-weight:600;\">装配多显卡的机器的顺序可能会有差异，需要自行测试。</span></p></body></html>"))
        self.cb_gpuid_sr.setItemText(0, _translate("MainWindow", "0"))
        self.cb_gpuid_sr.setItemText(1, _translate("MainWindow", "1"))
        self.cb_gpuid_sr.setItemText(2, _translate("MainWindow", "2"))
        self.cb_gpuid_sr.setItemText(3, _translate("MainWindow", "3"))
        self.cb_gpuid_sr.setItemText(4, _translate("MainWindow", "4"))
        self.label_14.setText(_translate("MainWindow", "切割大小:"))
        self.cb_tilesize.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">切割块大小，增大数值可以降低显存的占用。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">默认0为不切割，适用于大多数情况。</span></p></body></html>"))
        self.cb_tilesize.setItemText(0, _translate("MainWindow", "0"))
        self.cb_tilesize.setItemText(1, _translate("MainWindow", "100"))
        self.cb_tilesize.setItemText(2, _translate("MainWindow", "200"))
        self.cb_tilesize.setItemText(3, _translate("MainWindow", "400"))
        self.cb_tilesize.setItemText(4, _translate("MainWindow", "800"))
        self.cb_tilesize.setItemText(5, _translate("MainWindow", "1000"))
        self.rb_tta.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">TTA:</span></p><p><span style=\" font-size:10pt; font-weight:600;\">通过运行一些特定的策略推理来获得更好的渲染效果，会增加三到四倍的运行时间。</span></p></body></html>"))
        self.rb_tta.setText(_translate("MainWindow", "TTA增强"))
        self.groupBox.setTitle(_translate("MainWindow", "输出参数设置"))
        self.rb_save_alpha.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">对有Alpha通道的图片渲染后保留alpha通道</span></p></body></html>"))
        self.rb_save_alpha.setText(_translate("MainWindow", "是否保留alpha通道"))
        self.label_11.setText(_translate("MainWindow", "输出格式:"))
        self.cb_PicFormat.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">图片格式。</span></p><p><span style=\" font-size:10pt; font-weight:600;\">jpg和png为常用的格式。</span></p></body></html>"))
        self.cb_PicFormat.setItemText(0, _translate("MainWindow", "jpg"))
        self.cb_PicFormat.setItemText(1, _translate("MainWindow", "png"))
        self.label_12.setText(_translate("MainWindow", "jpg输出质量:"))
        self.sb_quality_jpg.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">JPG格式图片的质量参数</span></p><p><span style=\" font-size:10pt; font-weight:600;\">数值越大，质量越好，文件体积越大。</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "PNG压缩率"))
        self.sb_compress_png.setToolTip(_translate("MainWindow", "<html><head/><body><p>PNG格式图片的压缩质量参数</p><p>数值越大，压缩比越大。</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "输出文件夹："))
        self.out_folder.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">输出文件夹：</span></p><p><span style=\" font-size:10pt; font-weight:600;\">即图片输出后的保存目录</span></p></body></html>"))
        self.out_folder.setPlaceholderText(_translate("MainWindow", "可直接拖入文件夹"))
        self.select_of.setText(_translate("MainWindow", "选择文件夹"))
        self.stop_render.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">终止当前未完成的任务。如果没终止的话请到任务管理器关闭VSET.exe进程。</span></p></body></html>"))
        self.stop_render.setText(_translate("MainWindow", "终止任务"))
        self.start_render.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">点击这里启动渲染进程，</span></p><p><span style=\" font-size:10pt; font-weight:600;\">界面内显示渲染进度。</span></p></body></html>"))
        self.start_render.setText(_translate("MainWindow", "启动渲染"))
        self.te_show.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:15pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import icons_rc
